### ISSUE TITLE
Service vacuum.xiaomi_clean_zone is not working

### ISSUE THREAD

**Issue by Gooman-rus** [marotoweb/home-assistant-vacuum-viomise#15]
Trying to call the service to start `zone cleaning`:
```
service: vacuum.xiaomi_clean_zone
data:
  zone:
  - - -1.095378490775417
    - -1.5482420966157804
    - 0.6180019504671357
    - -0.7262265578801923
  repeats: 1
```

This call causes error in homeassistant logs and vacuum does not start cleaning:
```
Logger: custom_components.viomise.vacuum
Source: custom_components/viomise/vacuum.py:308
Integration: viomise (documentation, issues)
First occurred: 15:04:23 (3 occurrences)
Last logged: 15:04:42

Unable to clean zone: {'code': -9998, 'message': 'user ack invalid'}
```

Is there any way to fix the problem?

`Point cleaning` works fine:
```
service: vacuum.xiaomi_clean_point
data:
  point:
  - -0.39603960396039284
  - -0.6440594059405989
```
