### ISSUE TITLE
Platform error vacuum.viomise - cannot import name 'Vacuum' from 'miio'

### ISSUE THREAD

**Issue by kkarkos** [marotoweb/home-assistant-vacuum-viomise#19]
`Platform error vacuum.viomise - cannot import name 'Vacuum' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py)`

configuration.yml:
```
vacuum:
  - platform: viomise
    host: 192.168.52.62
    token: xxxx
    name: Viomi V3
```
Getting above Error with **Home Assistant Core 2022.5.3** - is it possible that the latest core package has some breaking changes?
