### ISSUE TITLE
Support for Automatic Switching Map uUsed by Viomi SE

### ISSUE THREAD

**Issue by ilhavo** [marotoweb/home-assistant-vacuum-viomise#22]
Hi, first of all thank you very much for your work.
I would like to know how I can change the map in the home assistant... I've already managed to add buttons, but when I click on it nothing happens..

If you change the map in "Mi Home APP" it will update in home assistant.

I currently have my card like this:

Thank you very much

[Card.txt](https://github.com/marotoweb/home-assistant-vacuum-viomise/files/9892352/Card.txt)

![Print](https://user-images.githubusercontent.com/38327099/198748235-bfa688aa-bac6-401d-87c9-ef43d9d861fe.png)

**Comment by nelsonpita** [comment]
Can you help me and send me an example of your configuration.yaml?

**Comment by marotoweb** [comment]
Hi! Thank you for the kind words and for using the integration.

In the old version (v1), in lovelace there isn't a dedicated button for map switching yet, but you can definitely do it using the viomise.send_command service. Since the Viomi SE (v19) uses specific internal IDs for each map, you first need to find out what those IDs are.

Theoretically it's possible following these untested procedures. The good news is that i'm working on v2 branch with the implementation of a specialized service to facilitate changes by map name, ID, or index #40 .


Step 1: Find your Map IDs

1. Go to Developer Tools > Services.
2. Select vacuum.send_command or viomise.send_command
3. Choose your vacuum entity.
4. Use get_map as the command.
5. Check your Home Assistant logs or the command output. You will see a JSON string containing your map names (e.g., "Map1", "Map2") and their corresponding IDs (long numbers).

Step 2: Create a Button to Switch Maps
Now that you have the IDs, you can configure your buttons to call the service. Here is an example of how the YAML for your button should look:


```YAML
show_name: true
show_icon: true
type: button
name: Switch to Upstairs
icon: mdi:map-marker-path
tap_action:
  action: call-service
  service: vacuum.send_command
  target:
    entity_id: vacuum.viomi_se  # Replace with your entity ID
  data:
    command: set_map
    params: [1776189566] # Replace with the ID you found in Step 1
```

For lovelace, you have this example based in a contribution from @divinezmuz for new v2

```YAML
square: false
type: grid
columns: 1
cards:
  - type: heading
    heading: Viomi SE
    icon: mdi:robot-vacuum
    heading_style: title
  - type: custom:xiaomi-vacuum-map-card
    entity: vacuum.viomi_se
    vacuum_platform: marotoweb/viomise
    map_source:
      camera: image.viomi_se_live_map
    calibration_source:
      camera: true
    tiles:
      - tile_id: status
        entity: sensor.viomi_status
        label: Status
      - tile_id: battery
        entity: sensor.viomi_battery
        label: Battery
      - tile_id: area
        entity: vacuum.viomi_se
        label: Area
        attribute: s_area
        unit: m²
        icon: mdi:texture-box
      - tile_id: time
        entity: vacuum.viomi_se
        label: Time
        attribute: s_time
        unit: min
        icon: mdi:clock-time-five-outline
      - tile_id: main_brush
        entity: vacuum.viomi_se
        label: Main Brush
        attribute: main_brush_left
        unit: h
        icon: mdi:brush-variant
      - tile_id: side_brush
        entity: vacuum.viomi_se
        label: Side Brush
        attribute: side_brush_left
        unit: h
        icon: mdi:brush
      - tile_id: filter
        entity: vacuum.viomi_se
        label: Filter
        attribute: filter_left
        unit: h
        icon: mdi:air-filter
      - tile_id: mop_life
        entity: vacuum.viomi_se
        label: Mop
        attribute: mop_left
        unit: h
        icon: mdi:format-color-fill
    append_icons: true
    icons:
      # --- NEW SECTION: MAP SELECTION ---
      - icon_id: map_ground_floor
        icon: mdi:layers-outline
        label: Ground Floor
        menu_id: map_selection
        tap_action:
          action: call-service
          service: vacuum.viomise_set_map
          service_data:
            entity_id: vacuum.viomi_se
            map_name: "Map1" # Replace with the actual name from get_map
      - icon_id: map_first_floor
        icon: mdi:layers-triple-outline
        label: First Floor
        menu_id: map_selection
        tap_action:
          action: call-service
          service: vacuum.viomise_set_map
          service_data:
            entity_id: vacuum.viomi_se
            map_name: "Map2"
      
      # --- CLEANING MODES ---
      - icon_id: mode_vacuum
        icon: mdi:vacuum
        label: Vacuum Only
        menu_id: cleaning_mode
        conditions:
          - entity: sensor.viomi_cleaning_mode
            value: vacuum
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.viomi_se
            command: set_mop
            params: [0]
      - icon_id: mode_mixed
        icon: mdi:hydro-power
        label: Vacuum & Mop
        menu_id: cleaning_mode
        conditions:
          - entity: sensor.viomi_cleaning_mode
            value: mixed
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.viomi_se
            command: set_mop
            params: [1]
      - icon_id: mode_mop
        icon: mdi:waves
        label: Mop Only
        menu_id: cleaning_mode
        conditions:
          - entity: sensor.viomi_cleaning_mode
            value: mop
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.viomi_se
            command: set_mop
            params: [2]

      # --- WATER LEVEL ---
      - icon_id: water_low
        icon: mdi:water-minus-outline
        label: Low
        menu_id: water_level
        conditions:
          - entity: sensor.viomi_water_level
            value: low
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.viomi_se
            command: set_suction
            params: [11]
      - icon_id: water_medium
        icon: mdi:water
        label: Medium
        menu_id: water_level
        conditions:
          - entity: sensor.viomi_water_level
            value: medium
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.viomi_se
            command: set_suction
            params: [12]
      - icon_id: water_high
        icon: mdi:water-plus
        label: High
        menu_id: water_level
        conditions:
          - entity: sensor.viomi_water_level
            value: high
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.viomi_se
            command: set_suction
            params: [13]

      # --- MOP PATTERN ---
      - icon_id: pattern_y
        icon: mdi:alpha-y-circle
        label: Y-shape
        menu_id: mop_pattern
        conditions:
          - entity: sensor.viomi_mop_pattern
            value: y_shape
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.viomi_se
            command: set_moproute
            params: [1]
      - icon_id: pattern_s
        icon: mdi:alpha-s-circle
        label: S-shape
        menu_id: mop_pattern
        conditions:
          - entity: sensor.viomi_mop_pattern
            value: s_shape
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.viomi_se
            command: set_moproute
            params: [0]

    map_modes:
      - name: Area Cleaning
        icon: mdi:select-drag
        selection_type: MANUAL_RECTANGLE
        max_selections: 5
        repeats_type: EXTERNAL
        max_repeats: 3
        service_call_schema:
          service: vacuum.viomise_clean_zone # Updated to v2 native service
          service_data:
            zone: "[[selection]]"
            repeats: "[[repeats]]"
            entity_id: vacuum.viomi_se
      - name: Point Cleaning
        icon: mdi:map-marker-plus
        selection_type: MANUAL_POINT
        service_call_schema:
          service: vacuum.viomise_clean_point # Updated to v2 native service
          service_data:
            point: "[[selection]]"
            entity_id: vacuum.viomi_se
```
Thank you for your patience
