### ISSUE TITLE
Cannot connect to vacuum

### ISSUE THREAD

**Issue by PieterGoossens** [marotoweb/home-assistant-vacuum-viomise#3]
Thanks for updating the installation instructions, installing it through HACS works like a charm! Unfortunately, my Viomi SE vacuum reports to be unavailable. My Xiaomi Mija 1S is working without any issues. I've extracted the tokens using the extractor script found here: https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor

```
$ python3 token_extractor.py
....
Server (one of: cn, de, us, ru, tw, sg, in, i2) Leave empty to check all available:

Logging in...
Logged in.

Devices found for server "cn":
   ---------
   NAME:  Vacuum-Upstairs
   ID:    2613xxxxx
   IP:    192.168.40.101
   TOKEN: 6e39xxxxxxxxxxxxxx6e4c
   MODEL: roborock.vacuum.m1s
   ---------

Devices found for server "de":
   ---------
   NAME:  Vacuum-Downstairs
   ID:    3754xxxxx
   IP:    192.168.40.102
   TOKEN: 5477xxxxxxxxxxxxxx6456
   MODEL: viomi.vacuum.v19
   ---------
```

After which I've added the following to `configuration.yaml` and restarted HA:

```
vacuum:
  - platform: xiaomi_miio
    host: 192.168.40.101
    token: 6e39xxxxxxxxxxxxxx6e4c
    name: Vacuum upstairs
  - platform: viomise
    host: 192.168.40.102
    token: 5477xxxxxxxxxxxxxx6456
    name: Vacuum downstairs
```

Any ideas why the Viomi vacuum doesn't work?
