### ISSUE TITLE
viomi.vacuum.v23 not supported

### ISSUE THREAD

**Issue by V1Studios** [marotoweb/home-assistant-vacuum-viomise#30]
I have the token acquired, and edited my Yaml to include the following :
```
vacuum:
  - platform: viomise
    host: 192.168.76.19
    token: 30715476556e437174xxxxxxxxxxb
    name: Jeeves
    # do not flood the vacuum with requests with scan_interval
    scan_interval: 30
```
but it cannot recognize the device
