### ISSUE TITLE
New  enhancements (Secondary cleaning switch and Mopping/sweeping route)

### ISSUE THREAD

**Issue by kodifan** [marotoweb/home-assistant-vacuum-viomise#9]
Halo 
any chance for adding two more enhancements for this integration?
- Secondary cleaning switch
- Mopping/sweeping route (0=S or Y=1)
I see those are available in both specifications_viomi_v13_1.yaml and specifications_viomi_v19_1.yaml files.

One more thing: is is possible to read light (vacuum led status) ? You can turn it off or on,  but i cant see such property either in your integration or specification file.

**Comment by marotoweb** [comment]
The two states can be easily implemented, in fact there are more values ​​that could be obtained without significantly decreasing the performance however the led status does not exist in the specifications

**Comment by kodifan** [comment]
Would be great;) more is always better;)

**Comment by marotoweb** [comment]
Check out https://github.com/marotoweb/home-assistant-vacuum-viomise/commit/ce38c4d4fc0b4fa3a077aa26f21b9e1bd960028e

**Comment by kodifan** [comment]
Hi Krzysztof, Im new in all this Home Assistant stuffs. So maybe I don't have knowledge to do this correctly but those attributes seems to be read only ? Is it the way to set them ? I don't set any set_route or set_repeat command in your vacuum.py file

**Comment by marotoweb** [comment]
Hi, I'm Roberto

In fact it is already possible to change any rewritable property values simply using the **vacuum.send_command** service

Script example: 
```yaml
alias: 'Change  repeat_state (1=on, 0=off)'
sequence:
  - data:
      command: set_properties
      params:
        - siid: 4
          piid: 1
          value: 1
    service: vacuum.send_command
    target:
      entity_id: vacuum.viomi_se
mode: single
```



![imagem](https://user-images.githubusercontent.com/4264711/119230379-d3602b80-bb13-11eb-9b99-7562ba132b81.png)
